vim.opt.autochdir       = false
vim.opt.autoindent      = true
vim.opt.autoread        = true
vim.opt.autowrite       = false
vim.opt.autowriteall	= false
vim.opt.background	= "dark"
vim.opt.backspace	= "indent,eol,start"
vim.opt.backup		= false
vim.opt.backupcopy	= "no"
vim.opt.backupdir	= "/home/josema/.cache/nvim/backup//"
vim.opt.backupext	= "~"
vim.opt.backupskip	= "$TMPDIR/*,$TMP/*,$TEMP/*"
vim.opt.belloff		= "all"
vim.opt.binary		= false
vim.opt.bomb		= false
vim.opt.breakat		= " ^!@*-+;:,./?"
vim.opt.breakindent	= true
vim.opt.breakindentopt	= ""
vim.opt.bufhidden	= ""
vim.opt.buflisted	= true
vim.opt.buftype		= ""
vim.opt.casemap		= "internal,keepascii"
vim.opt.cdpath		= ",,"
vim.opt.cedit		= "<C-F>"
vim.opt.charconvert	= ""
-- vim.opt.channel		= 0
vim.opt.cindent		= false
vim.opt.cinkeys		= "0{,0},0),0],:,0#,!^F,o,O,e"
vim.opt.cinoptions	= ""
vim.opt.cinscopedecls	= "public,protected,private"
vim.opt.cinwords	= "if,else,while,do,for,switch"
vim.opt.clipboard	= "unnamedplus"
vim.opt.cmdheight	= 1
vim.opt.cmdwinheight	= 3
vim.opt.colorcolumn	= ""
-- vim.opt.columns		= 80
vim.opt.comments	= "s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-,fb:•"
vim.opt.commentstring	= ""
vim.opt.complete	= ".,w,b,u,t"
vim.opt.completefunc	= ""
vim.opt.completeopt	= "menu,preview"
-- vim.opt.completeslash	= ""
vim.opt.concealcursor	= ""
vim.opt.conceallevel	= 0
vim.opt.confirm		= true
vim.opt.copyindent	= true
vim.opt.cpoptions	= "aABceFs_"
vim.opt.cursorbind	= false
vim.opt.cursorcolumn	= false
vim.opt.cursorline	= false
vim.opt.cursorlineopt	= "both"
vim.opt.debug		= ""
vim.opt.define		= ""
vim.opt.delcombine	= false
vim.opt.dictionary	= ""
vim.opt.diff		= false
vim.opt.diffexpr	= ""
vim.opt.diffopt		= "internal,filler,closeoff"
vim.opt.digraph		= false
vim.opt.directory	= "/home/josema/.local/state/nvim/swap//"
vim.opt.display		= "lastline"
vim.opt.eadirection	= "both"
vim.opt.emoji		= true
vim.opt.encoding	= "utf-8"
vim.opt.endoffile	= false
vim.opt.endofline	= true
vim.opt.equalalways	= true
vim.opt.equalprg	= ""
vim.opt.errorbells	= false
vim.opt.errorfile	= "errors.err"
-- vim.opt.errorformat = _A very long string_
vim.opt.eventignore	= ""
vim.opt.expandtab	= true
vim.opt.exrc            = false
vim.opt.fileencoding    = "uft-8"
vim.opt.fileencodings   = "ucs-bom,utf-8,default,latin1"
vim.opt.fileformat      = "unix"
vim.opt.fileformats     = "unix,dos"
-- vim.opt.fileignorecase = true ¿?
vim.opt.filetype        = ""
vim.opt.fillchars       = ""
vim.opt.fixendofline    = true
vim.opt.foldclose       = ""
vim.opt.foldcolumn      = "auto"
vim.opt.foldenable      = true
vim.opt.foldexpr        = "0"
vim.opt.foldignore      = "#"
vim.opt.foldlevel       = 0
vim.opt.foldlevelstart  = -1
vim.opt.foldmarker      = "{{{,}}}"
vim.opt.foldmethod      = "manual"
vim.opt.foldminlines    = 1
vim.opt.foldnestmax     = 20



vim.opt.linebreak	= true

